### PR TITLE
limiter: exemption conditions for limits

### PR DESCRIPTION
**Pull request by SamiHiltunen**
# Exemption Conditions

I recently bumped in to a need to limit requests by different conditions being true or false. This pull request adds support for giving each limit a condition that checks whether the current request should be exempted of the limit or not.

## Why?

Allows users to fine tune when a request should be exempted of a specific limit . Some use cases might include different quotas for different users in different groups.

## How? 

When you limit a route, you can optionally give a parameter called ```exempt_when```. It should be a callable that returns a boolean with ```True``` indicating the current request is exempted of the limit and ```False``` indicating the limit is enforced normally.

Example usage:
```Python
@app.route('/expensive')
@limiter.limit('1 per day', exempt_when=lambda: user.is_admin)
def expensive_function():
    """Super expensive function that eats all the resources."""
    while True:
        pass
```

### CODE REVIEW

**Comment by alisaifee** [comment]
Thanks, the proposal and implementation look good to me overall.

One change I would like to request is to rename the parameter to `exempt_when` and invert the logic. This is firstly to stay consistent with the `exempt` decorator and also to be able to use a `None` as the default value so that a quick short circuit can be performed for the default case where no callable is provided.

```python
@property
def is_exempt(self):
    return self.exempt_when and self.exempt_when()
```

Could I also request that you add an example under decorators in `doc/sources/index.rst` for this use case?

**Comment by SamiHiltunen** [comment]
Thanks for the comments @alisaifee. I've made the changes you proposed. Let me know you find anything else.

**Comment by alisaifee** [comment]
Looks good! I'll make a release by EOD.

**Comment by alisaifee** [comment]
Released in version `0.9`. Thank you for your contribution!

**Pull request merged**
