### PR TITLE
Optimize limit exemption by key func

### PR DESCRIPTION
**Pull request by cmin764**
This PR changes a little the order of `args` checks in order to get the key function before the exemption status.

This helps people design their rate-limiting at request time while they want exemption based on some DB transactions, like so:

1. Let's say we decide the exemption at request time if we were able to find in the DB what the user was looking for, otherwise we don't want to count that request against the limit. (so clients get counted for valuable received data only)
2. But since the exemption polls the DB, this takes time and this replicates for any string limits you want to skip, which can be a LOT.
3. Why having a LOT of limits that can be skipped? Because for each client you may want to have a different limit, so you decorate the function with all of them and once a client hits the function, you check the limits based on the request data and just for one of them you return a not `None` key_func return value.
4. This change checks the key values first, skips all of them beside one (the one targeting the client) and then you proceed further with exemption check and so on.

----

Question: Is it possible to find some other (simpler) way of applying a custom limit depending on the requesting client?
Real-life scenario: we have trial clients, premium clients, corporate ones and all of them are paying differently for the service, thus having a custom limit for each requester. They are identified through a token at request time and only then we can figure out what limit applies, therefore we want to apply that specific limit only, but since we're using a Flask Resource GET API method, we should decorate this in advance through `decorators`. (the problem is we can decorate correctly at request time only, therefore that's why the workaround above of decorating from the start with all the limits we've got and at request time decide what's the specific one based on the provided token by the client)

Any kind of input will be much appreciated!

### CODE REVIEW

**Comment by alisaifee** [comment]
Perhaps I misunderstood the requirements but why is it more expensive to perform the exemption through an `exempt_when` callback versus returning `None` from `key_func`. 

I wouldn't recommend depending on the return from `key_func` for business logic, and the scenario where it returns `None` should be treated as an error condition (if you were to use this approach your logs would be littered with `ERROR` level log entries).

For a given route or set of routes, if you want to decide on which rate limit to apply based on the request/requesting user, using a single decorator with a dynamic limit retrieved by providing a function instead of a rate limit string makes most sense. 

For example:

```python
from flask import Flask, request
from flask_limiter import Limiter
from flask_restful import Api as RestfulApi, Resource

app = Flask(__name__)
limiter = Limiter(app)
api = RestfulApi(app)

def limit_func():
    token = request.headers.get("token", "")

    if token == "admin":
        return "4/second"
    elif token == "corporate":
        return "3/minute"
    elif token == "guest":
        return "2/minute"
    else:
        return "1/minute"


class MyResource(Resource):
    decorators = [limiter.limit(limit_func)]

    def get(self):
        return "42"



app.add_url_rule("/", view_func=MyResource.as_view("resource"))
app.run(debug=True)
```

**Comment by cmin764** [comment]
You example solves all my issues and their workaround, I didn't know you can set dynamic limits at request time. This is a very important example that should appear in the README/docs though if it's not there yet.

Thank you and you can close this MR if it doesn't bring any value!

**Comment by alisaifee** [comment]
@cmin764 I'm glad using dynamic limit works for your use case. You're right that this way of using the decorator isn't obvious from the README (the docs for the decorator [here](https://flask-limiter.readthedocs.io/en/stable/#decorators) is where it is documented). I'll probably work on a README example that covers a lot more of the functionality instead of just the most common ones.

Regarding your pull request, I do really prefer the early exit that you have done. If you could rebase your branch against master and revert the change of order of checks (i.e. revert to `exempt` first and then check `args`) I'll be happy to merge this.

**Comment by alisaifee** [comment]
Picked some of the changes in 28ed8bb7e49e706d935c6fb16ad1921a07bdb65e

**Pull request closed without merging**
